### ISSUE TITLE
Fatal error: Class 'PDO' not found in /home/xxxx/models/rb.php on line 365

### ISSUE THREAD

**Issue by sonamkabra** [elinoretenorio/jobskee-open-source-job-board#12]
hello elinoretenorio, 
i was install jobskee using http://www.jobskee.com/download.php
 webite and instructions. 
i was follow all step as given .
after that i was run my site its gives me a fatal error: 
Fatal error: Class 'PDO' not found in /home/xxxx/models/rb.php on line 365

i am also trying to open rb.php file but it can't open . all time my browser give a notification is cant not support or some time not responding the browser. i was change all thing you mention in your code. 
please give me some idea to solve this error.
my email id : sonam.kabra90@gmail.com

![capture](https://cloud.githubusercontent.com/assets/19326534/15214814/df2a2f5a-186c-11e6-9e67-33db1d36487c.JPG)

**Comment by elinoretenorio** [comment]
this means you do not have PDO module enabled in your hosting environment. you need PDO extension enabled in your hosting to use Jobskee

http://php.net/manual/en/pdo.installation.php
