### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by wondersoftheworld** [elinoretenorio/jobskee-open-source-job-board#17]
When user posts a job and selects an image to be posted with the job listing, the image is broken on frontend. How to fix this? Thanks

**Comment by sourcem2c** [comment]
1. Goto directory /assets/images
2. Open .htaccess
3. Insert code below and images will start displaying

```
#php_flag engine off
#AddHandler cgi-script .php .php3 .php4 .phtml .pl .py .jsp .asp .aspx .htm .html .shtml .sh .cgi
#Options -Indexes -ExecCGI

## Jobskee's .htaccess bug

RewriteEngine on
RewriteCond %{REQUEST_URI} ^upload\/members\/.*\.(gif|jpe?g|png)$ [NC]
RewriteRule .? - [F,L]
```

I referred this article (link mentioned below) and code is also copy/paste from it. It worked for me but you can change it as per your convenience.

[https://www.sitepoint.com/community/t/htaccess-to-only-allow-images-to-display-in-directory/5606/3](https://www.sitepoint.com/community/t/htaccess-to-only-allow-images-to-display-in-directory/5606/3)

**Comment by mittaltiger** [comment]
I referred this article and code is also copy/paste from it. It worked for me but you can change it as per your convenience.
