### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by silicon755** [elinoretenorio/jobskee-open-source-job-board#24]
How do I solve;
"The requested URL /categories/1/programming was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request."

**Comment by jobskee** [comment]
You need to make sure that mod_rewrite is enabled in your hosting server.

**Comment by devasia2112** [comment]
Any idea how i can get it working with nginx? 
i converted the rules from apache to nginx, but it returns just 404 error.
`
location / {
  if (!-e $request_filename){
    rewrite ^(.*)$ /index.php break;
  }
}
`
cheers!
