### ISSUE TITLE
csv upload not working

### ISSUE THREAD

**Issue by techlearnBDC** [elinoretenorio/jobskee-open-source-job-board#25]
As admin I go to 
/admin/jobs/upload
and I upload jobs using a formatted .csv file but keep getting the flash error 'Invalid CSV file upload'.

I have validated the csv and its in the correct format and has correct number of fields as per 
// check if the csv file has the right number of fields
                        if (count($data) == CSV_FIELDS) {

any ideas?

**Comment by silicon755** [comment]
Hey buddy, I can't get mine up to run. Kindly help

**Comment by jobskee** [comment]
@techlearnBDC - In order to bypass the file type check (on Line 223 of **/controllers/admin.php**)
```
if ($data['type'] == 'text/csv' && move_uploaded_file($file['tmp_name'], $csv)) {
```
Just remove the data type check, so it will now be:
```
if (move_uploaded_file($file['tmp_name'], $csv)) {
```
